all:
  children:
    site:
      hosts:
        srv15.mikr.us:
          ansible_user: root
          ansible_port: 10107  # This line is commented out; remove the hash to activate the port configuration
    arch:
      hosts:
        maluch.mikr.us:
          ansible_user: root
          ansible_port: 10780
    backup:
      hosts:
        maluch2.mikr.us:
          ansible_user: root
          ansible_port: 10492
    raspberrypi:
      hosts:
        raspberrypi:
          ansible_user: pi
          ansible_host: 192.168.0.251
