all:
  hosts:
    mikrus:
      ansible_host: srv15.mikr.us
      ansible_user: root
      ansible_port: 10107
    raspberrypi:
      ansible_user: pi
      ansible_host: 192.168.0.222
    workstation:
      ansible_host: fedora
