- name: Create new ansible user
  become: true
  ansible.builtin.user:
    name: "{{ setup_ansible_usr_name | default('ansible') }}"
    state: present

- name: Add ssh key to authorized_keys
  become: true
  ansible.builtin.lineinfile:
    path: "/home/{{ setup_ansible_usr_name | default('ansible') }}/.ssh/authorized_keys"
    line: "{{ item }}"
    state: present
    create: true
    mode: "600"
    owner: "{{ setup_ansible_usr_name | default('ansible') }}"
    group: "{{ setup_ansible_usr_name | default('ansible') }}"
  loop:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKnn1RaiJ1G2HdUhxG3fDM3RtC5YR7p+hvgFGm+FWYMp simon@hryszko.dev"

- name: Register groups
  getent:
    database: group

- name: "Set ansible user's groups if exists on the system"
  become: true
  user:
    name: "{{ setup_ansible_usr_name | default('ansible') }}"
    append: true
    groups: "{{ item }}"
  loop:
    - sudo
    - wheel
    - adm
    - systemd-journal
    - sys
  when: item in ansible_facts.getent_group

- name: Set sudoer for ansible user
  become: true
  community.general.sudoers:
    name: "{{ setup_ansible_usr_name | default('ansible') }}"
    user: "{{ setup_ansible_usr_name | default('ansible') }}"
    commands: ALL
    runas: ALL
  