# Use the official Ubuntu base image
FROM ubuntu:latest

# Update package list
RUN apt-get update

# Set TZ to amsterdam
ENV TZ=Europe/Amsterdam
ENV DEBIAN_FRONTEND=noninteractive

# Install ansible, ssh and python3-pip
RUN apt-get install -y ansible ssh python3-pip

# Set working directory
WORKDIR /ansible

# Copy your Ansible configurations
COPY . /ansible

# Run bash so we can interact with the container
CMD ["/bin/bash"]