---
- include_tasks: gen_n8n_files.yml
  when: n8n_state == "present"

- name: Create /etc/nginx/sites-available dir
  ansible.builtin.file:
    path: /etc/nginx/sites-available
    state: directory
  when: n8n_state == "present"

- name: Create nginx config
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ n8n_domain }}"
  tags: n8n, nginx
  notify: Reload nginx
  when: n8n_state == "present"

- name: Create /etc/nginx/sites-enabled dir
  file:
    path: /etc/nginx/sites-enabled
    state: directory
  when: n8n_state == "present"

- name: Enable nginx config
  file:
    src: "/etc/nginx/sites-available/{{ n8n_domain }}"
    dest: "/etc/nginx/sites-enabled/{{ n8n_domain }}"
    state: link
  tags: n8n, nginx
  when: n8n_state == "present"

