---
- debug: { var: SEMAPHORE_PATH }

- name: gen_semaphore_files | Make directory for semaphore
  file:
    path: "{{ SEMAPHORE_PATH }}"
    state: directory
  tags: semaphore

- name: gen_semaphore_files | Generate docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ SEMAPHORE_PATH }}/docker-compose.yml"
  notify: Restart Semaphore
  tags: semaphore

- import_tasks: gen_semaphore_envs.yml
  notify: Restart Semaphore
