---
- include_tasks: _register_grep_in_grep_file
  vars:
    grep_regex: "SEMAPHORE_PORT=.*"

- name: gen_semaphore_envs | Generate password for SEMAPHORE_ADMIN_PASSWORD
  ansible.builtin.shell: echo "SEMAPHORE_ADMIN_PASSWORD=$(cat /dev/urandom | tr -dc a-zA-Z0-9 | head -c64; echo)" >> "{{ GREP_FILE }}"
  when: grep_result.stdout == ""


- include_tasks: _register_grep_in_grep_file
  vars:
    grep_regex: "SEMAPHORE_PORT=.*"

- name: gen_semaphore_envs | Add default 3000 port to SEMAPHORE_PORT
  ansible.builtin.shell: echo "SEMAPHORE_PORT=3000" >> "{{ GREP_FILE }}"
  when: grep_result.stdout == ""


- include_tasks: _register_grep_in_grep_file
  vars:
    grep_regex: "SEMAPHORE_ADMIN_NAME=.*"

- name: gen_semaphore_envs | Set SEMAPHORE_ADMIN_NAME to ansible_user
  ansible.builtin.shell: echo "SEMAPHORE_ADMIN_NAME={{ SEMAPHORE_ADMIN_NAME | default(ansible_user) }}" >> "{{ GREP_FILE }}"
  when: grep_result.stdout == ""


- include_tasks: _register_grep_in_grep_file
  vars:
    grep_regex: "SEMAPHORE_ADMIN_DOMAIN=.*"

- name: gen_semaphore_envs | Set SEMAPHORE_ADMIN_DOMAIN to ansible_hostname
  ansible.builtin.shell: echo "SEMAPHORE_ADMIN_DOMAIN={{ ansible_hostname }}" >> "{{ GREP_FILE }}"
  when: grep_result.stdout == ""


- include_tasks: _register_grep_in_grep_file
  vars:
    grep_regex: "SEMAPHORE_ACCESS_KEY_ENCRYPTION=.*"

- name: gen_semaphore_envs | Generate SEMAPHORE_ACCESS_KEY_ENCRYPTION with /dev/random 
  ansible.builtin.shell: echo "SEMAPHORE_ACCESS_KEY_ENCRYPTION=$(head -c32 /dev/urandom | base64)" >> "{{ GREP_FILE }}"
  when: grep_result.stdout == ""
