---
- set_fact: { _grep_file: "{{ SEMAPHORE_PATH }}/.env" }
- include_tasks: _register_grep_in_grep_file.yml
  vars:
    _grep_regex: "SEMAPHORE_PORT=.*"

- name: gen_semaphore_envs | Generate password for SEMAPHORE_ADMIN_PASSWORD env
  ansible.builtin.shell: echo "SEMAPHORE_ADMIN_PASSWORD=$(cat /dev/urandom | tr -dc a-zA-Z0-9 | head -c64; echo)" >> "{{ _grep_file }}"
  when: _grep_result.stdout == ""


- include_tasks: _register_grep_in_grep_file.yml
  vars:
    _grep_regex: "SEMAPHORE_PORT=.*"

- name: gen_semaphore_envs | Add default 3000 port to SEMAPHORE_PORT env
  ansible.builtin.shell: echo "SEMAPHORE_PORT=3000" >> "{{ _grep_file }}"
  when: _grep_result.stdout == ""


- include_tasks: _register_grep_in_grep_file.yml
  vars:
    _grep_regex: "SEMAPHORE_ADMIN_NAME=.*"

- name: gen_semaphore_envs | Set SEMAPHORE_ADMIN_NAME to ansible_user
  ansible.builtin.shell: echo "SEMAPHORE_ADMIN_NAME={{ SEMAPHORE_ADMIN_NAME | default(ansible_user) }}" >> "{{ _grep_file }}"
  when: _grep_result.stdout == ""


- include_tasks: _register_grep_in_grep_file.yml
  vars:
    _grep_regex: "SEMAPHORE_ADMIN_DOMAIN=.*"

- name: gen_semaphore_envs | Set SEMAPHORE_ADMIN_DOMAIN to ansible_hostname
  ansible.builtin.shell: echo "SEMAPHORE_ADMIN_DOMAIN={{ ansible_hostname }}.local" >> "{{ _grep_file }}"
  when: _grep_result.stdout == ""


- include_tasks: _register_grep_in_grep_file.yml
  vars:
    _grep_regex: "SEMAPHORE_ACCESS_KEY_ENCRYPTION=.*"

- name: gen_semaphore_envs | Generate SEMAPHORE_ACCESS_KEY_ENCRYPTION with /dev/random 
  ansible.builtin.shell: echo "SEMAPHORE_ACCESS_KEY_ENCRYPTION=$(head -c32 /dev/urandom | base64)" >> "{{ _grep_file }}"
  when: _grep_result.stdout == ""
