- name: Register if "{{ansible_user_dir}}/.zshrc" exists
  stat:
    path: "{{ansible_user_dir}}/.zshrc"
  register: zshrc_file

- name: Download Oh My Zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh
  when: zshrc_file.stat.exists == False

- name: Run Oh My Zsh installation script
  command: sh /tmp/install_ohmyzsh.sh --unattended
  register: ohmyzsh_result
  failed_when: "'FAILED' in ohmyzsh_result.stderr"
  when: zshrc_file.stat.exists == False

- name: Add setting export TERM=xterm
  lineinfile:
    path: "{{ansible_user_dir}}/.zshrc"
    line: "export TERM=xterm"
    state: present

- name: Install fzf (command-line fuzzy finder)
  become: true
  ansible.builtin.package:
    state: present
    name: fzf

- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Clone oh-my-zsh plugins
  ansible.builtin.git:
    repo: https://github.com/zsh-users/{{ item }}
    dest: ~/.oh-my-zsh/custom/plugins/{{ item }}
    depth: 1
  loop: "{{ omz_repos }}"