- hosts: all
  roles:
  # - setup
  # - zsh
  # - install_docker

- hosts: [raspberrypi]
  roles:
    - semaphore

- hosts: [mikrus]
  vars:
    n8n_domain: n8n.hryszko.dev
    n8n_port: 20107
  roles:
    - n8n

- hosts: [ workstation ]
  roles:
    - workstation-setup

