---
- debug: { var: SEMAPHORE_PATH }

- name: Make directory for semaphore
  ansible.builtin.file:
    path: "{{ SEMAPHORE_PATH }}"
    state: directory
  tags: semaphore

- name: Generate docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ SEMAPHORE_PATH }}/docker-compose.yml"
  tags: semaphore

- import_tasks: gen_semaphore_envs.yml
  notify: Restart Semaphore
