- name: Override powerline fonts package name for Debian.
  ansible.builtin.set_fact:
    powerlinefonts: fonts-powerline
  when: ansible_os_family == 'Debian'

- name: Override fd-find package name for Archlinux.
  ansible.builtin.set_fact:
    fdfind: fd
  when: ansible_os_family == 'Archlinux'

- name: Install Powerline fonts
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ powerlinefonts }}"

- name: Install Google Noto emoji fonts
  become: true
  ansible.builtin.package:
    state: present
    name: noto-fonts-emoji
  when: ansible_os_family == 'Archlinux'

# To get "icons" in exa output
- name: Install Patched font Arimo from nerd-fonts (Arch)
  become: true
  ansible.builtin.package:
    state: present
    name: ttf-arimo-nerd
  when: ansible_os_family == 'Archlinux'
