---
- name: Update system
  become: true
  ansible.builtin.package:
    state: latest
    name: "*"
    update_cache: yes

- name: Install fonts
  ansible.builtin.include_tasks: fonts.yml
  when: IS_SERVER == "False"

- name: Install tools
  ansible.builtin.include_tasks: tools.yml

- name: "set timezone to TIMEZONE"
  become: true
  timezone:
    name: "{{ TIMEZONE }}"
  tags: timezone, tz

# - name: "Include role install_docker"
#   ansible.builtin.import_role:
#     name: install_docker
#   tags: docker
