---
- name: Get hostname
  command: "hostname -f"
  register: hostname
  changed_when: false

- name: "Print info about variables what this role will use"
  debug:
    msg: "{{ item.key }}: {{ item.value }}"

  loop:
    - { key: "hostname", value: "{{ hostname.stdout }}" }
    - { key: "ansible_user_dir", value: "{{ ansible_user_dir }}" }
    - { key: "CONFIG_DIR", value: "{{ CONFIG_DIR }}" }
    - { key: "CONFIG_FILE", value: "{{ CONFIG_FILE }}" }

- name: "Create config directory"
  file:
    path: "{{ CONFIG_DIR }}"
    state: directory
    mode: 0755

- name: "Create config file"
  file:
    path: "{{ CONFIG_FILE }}"
    state: touch
    mode: 0644

- name: setup | default_config | add keys to config file
  block:
    - name: setup | default_config | add keys to config file | grep
      ansible.builtin.command: "grep '^OPS_BRANCH:' {{ CONFIG_FILE }}"
      register: ops_branch_check
      failed_when: false
      changed_when: false
      ignore_errors: true

    - name: setup | default_config | add keys to config file | lineinfile
      ansible.builtin.lineinfile:
        path: "{{ CONFIG_FILE }}"
        line: "OPS_BRANCH: master"
        state: present
        create: yes
      when: ops_branch_check.rc != 0
