---
- name: Get hostname
  command: "hostname -f"
  register: hostname
  changed_when: false

- name: "Print info about variables what this role will use"
  debug:
    msg: "{{ item.key }}: {{ item.value }}"

  loop:
    - { key: "hostname", value: "{{ hostname.stdout }}" }
    - { key: "ansible_user_dir", value: "{{ ansible_user_dir }}" }
    - { key: "CONFIG_DIR", value: "{{ CONFIG_DIR }}" }
    - { key: "CONFIG_FILE", value: "{{ CONFIG_FILE }}" }
