---
- name: Get hostname
  command: "hostname -f"
  register: hostname
  changed_when: false

- name: "Print info with hostname and config dir"
  debug:
    msg: "Running setup playbook for hostnames: {{ hostname.stdout }}"

- name: Setup config file
  include_tasks: setup_config_file.yml
