---
- name: Get hostname
  command: "hostname -f"
  register: hostname
  changed_when: false

- name: "Print info about variables what this role will use"
  debug:
    msg: "{{ item.key }}: {{ item.value }}"

  loop:
    - { key: "hostname", value: "{{ hostname.stdout }}" }
    - { key: "ansible_user_dir", value: "{{ ansible_user_dir }}" }
    - { key: "CONFIG_DIR", value: "{{ CONFIG_DIR }}" }
    - { key: "CONFIG_FILE", value: "{{ CONFIG_FILE }}" }

- name: "Create config directory"
  file:
    path: "{{ CONFIG_DIR }}"
    state: directory
    mode: 0755

- name: "Add keys to config file"
  include_tasks: add_keys.yml
  vars:
    item_key: "{{ item.key }}"
    item_value: "{{ item.value }}"
  loop:
    - { key: "OPS_BRANCH", value: "master" }
    - { key: "OPS_REPO", value: "git@github.com:shirobachi/Aria.git" }