- name: Install ripgrep
  become: true
  ansible.builtin.package:
    state: present
    name: ripgrep

- name: Install procs in Arch/Fedora
  become: true
  ansible.builtin.package:
    state: present
    name: procs
  tags: procs
  when: ansible_os_family != 'Debian'

- name: Install unzip
  become: true
  ansible.builtin.package:
    state: present
    name: unzip
  when: IS_SERVER == "False"

- name: Install procs in Ubuntu
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/dalance/procs/releases/download/{{ procsversion }}/procs-{{ procsversion }}-{{ ansible_userspace_architecture }}-linux.zip"
    dest: /usr/local/bin
    remote_src: true
  tags: procs
  when: ansible_os_family == 'Debian'

- name: Install dust on Arch
  become: true
  ansible.builtin.package:
    state: present
    name: dust
  when: ansible_os_family == 'Archlinux'

- name: Install dust on Ubuntu/Fedora
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/bootandy/dust/releases/download/{{ dustversion }}/dust-{{ dustversion }}-{{ ansible_userspace_architecture }}-unknown-linux-gnu.tar.gz"
    dest: /usr/local/bin
    extra_opts:
    - --strip=1
    - --wildcards
    - '*/dust'
    remote_src: true
  when: ansible_os_family != 'Archlinux'

# In Ubuntu/Fedora we have to install it from archive
# so it's better to check if it's already installed
- name: Check if dust is already installed on Ubuntu/Fedora
  ansible.builtin.shell: >
    dust --version
  register: dust_rc
  failed_when: false
  changed_when: false
  when: ansible_os_family != 'Archlinux'
 
- name: Install dust on Ubuntu/Fedora
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/bootandy/dust/releases/download/{{ dustversion }}/dust-{{ dustversion }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: /usr/local/bin
    extra_opts:
    - --strip=1
    - --wildcards
    - '*/dust'
    remote_src: true
  when: ansible_os_family != 'Archlinux' and dust_rc.rc != 0

- name: Install exa (debian)
  become: true
  ansible.builtin.package:
    state: present
    name: exa
  when: ansible_os_family == 'Debian'

- name: Install exa on Arch Linux
  when: ansible_os_family == 'Archlinux'
  block:
    - name: Ensure base-devel is installed
      pacman:
        name: base-devel
        state: present
      become: true

    - name: Check if yay is installed
      command: which yay
      register: yay_check
      ignore_errors: true
      changed_when: false

    - name: Install yay if not present
      block:
        - name: Clone yay repository
          git:
            repo: https://aur.archlinux.org/yay.git
            dest: /tmp/yay
          become: true
          become_user: "{{ ansible_user_id }}"

        - name: Build and install yay
          command: makepkg -si --noconfirm
          args:
            chdir: /tmp/yay
          become: true
          become_user: "{{ ansible_user_id }}"
      when: yay_check.rc != 0

    - name: Install exa using yay
      command: yay -S exa --noconfirm
      become: true
      become_user: "{{ ansible_user_id }}"

  rescue:
    - name: Inform about failure
      debug:
        msg: "Failed to install exa. Please check your system and try again."

- name: Override fd-find package name for Archlinux.
  ansible.builtin.set_fact:
    fdfind: fd
  when: ansible_os_family == 'Archlinux'

- name: Install fd-find
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ fdfind }}"

- name: Create link fd to fdfind in Debian
  become: true
  ansible.builtin.file:
    src: '/usr/bin/fdfind'
    dest: '/usr/bin/fd'
    state: link
  when: ansible_os_family == 'Debian'

- name: Install bat
  become: true
  ansible.builtin.package:
    state: present
    name: bat

- name: Create link bat to batcat in Debian
  become: true
  ansible.builtin.file:
    src: '/usr/bin/batcat'
    dest: '/usr/bin/bat'
    state: link
  when: ansible_os_family == 'Debian' and ansible_distribution_version is version('23.04', '<')

# - name: Install zoxide
#   become: true
#   ansible.builtin.package:
#     state: present
#     name: zoxide