- name: Install ripgrep
  become: true
  ansible.builtin.package:
    state: present
    name: ripgrep

- name: Install procs in Arch/Fedora
  become: true
  ansible.builtin.package:
    state: present
    name: procs
  tags: procs
  when: ansible_os_family != 'Debian'

- name: Install unzip
  become: true
  ansible.builtin.package:
    state: present
    name: unzip
  when: IS_SERVER == "False"

- name: Install procs in Ubuntu
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/dalance/procs/releases/download/{{ procsversion }}/procs-{{ procsversion }}-{{ ansible_userspace_architecture }}-linux.zip"
    dest: /usr/local/bin
    remote_src: true
  tags: procs
  when: ansible_os_family == 'Debian'

- name: Install dust on Arch
  become: true
  ansible.builtin.package:
    state: present
    name: dust
  when: ansible_os_family == 'Archlinux'

- name: Install dust on Ubuntu/Fedora
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/bootandy/dust/releases/download/{{ dustversion }}/dust-{{ dustversion }}-{{ ansible_userspace_architecture }}-unknown-linux-gnu.tar.gz"
    dest: /usr/local/bin
    extra_opts:
    - --strip=1
    - --wildcards
    - '*/dust'
    remote_src: true
  when: ansible_os_family != 'Archlinux'
