- name: Make sure Semaphore running
  community.docker.docker_compose_v2:
    project_src: "{{ SEMAPHORE_PATH }}"

- name: Restart Semaphore
  community.docker.docker_compose_v2:
    project_src: "{{ SEMAPHORE_PATH }}"
    state: restarted
